### ISSUE TITLE
Retrieving text from the tabpane, inside of the terminal

### ISSUE THREAD

**Issue by Jovonni** [javaterminal/TerminalFX#1]
We have tried many methods on the tabpane itself, and on the terminal, but we aren't seeing how to actually get the terminal text that is on the line.

We are detecting when a user pressed enter, or return, but to retrieve that text is something we are having an issue with.

Any ideas?

Great work

**Comment by rahmanusta** [comment]
Hi @Jovonni,  I didn't understand your question.  Do you mean copy paste on Terminal?

**Comment by Jovonni** [comment]
No sir,

I mean if I want to fetch the text, that a user is typing into the terminal. The actual text that was typed into the terminal.

Pretend I want to detect whether a user typed "pwd", "Ls", or "mkdir" etc....

Thank you

On Dec 10, 2016, at 7:58 PM, Rahman Usta <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Jovonni<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJovonni&data=01%7C01%7Cjpharr2%40student.gsu.edu%7C8d1223fe8141444c3c1a08d42179e7fd%7C704d822c358a47849a1649e20b75f941%7C0&sdata=AcYIEem4pklEC7%2BkgR0s96MTcKLsnW70hoaXGoT9gC0%3D&reserved=0>, I didn't understand your question. Do you mean copy paste on Terminal?

-

**Comment by rahmanusta** [comment]
You will get each key from keyboard here https://github.com/rahmanusta/TerminalFX/blob/master/src/main/java/com/terminalfx/TerminalTab.java#L208, you should buffer characters until /r /n.

**Comment by Jovonni** [comment]
I was thinking about that as a final option... Interesting that that's the only way to get it. I might extend this to put that in there.

Thank you for your thoughts sir. Awesome work.
