### ISSUE TITLE
TerminalView

### ISSUE THREAD

**Issue by sirolf2009** [javaterminal/TerminalFX#13]
I'm trying to show some logs from an application running in production. I've got a jsch connection, so all I really need to do is redirect a stream to something that resembles a terminal. Right now I need to spawn a tab pane to have a tab, to have a terminal which accepts user input. But what I want is something like a popup displaying ANSI colored text. Could you separate the ANSI compliant terminal into a standalone view, something like TerminalView?

**Comment by rahmanusta** [comment]
Hi @sirolf2009, you can make pull requests for design changes.

**Comment by sirolf2009** [comment]
https://github.com/javaterminal/TerminalFX/pull/14
