### ISSUE TITLE
Blank terminal

### ISSUE THREAD

**Issue by oskarmolander2** [javaterminal/TerminalFX#20]
When I create a new terminaltab the terminal is completely empty. 
OnTerminalFxReady never fires.

using  jdk 11 / javafx 11.
code:
		
```
		TerminalBuilder builder = new TerminalBuilder();
		TerminalTab terminalTab = builder.newTerminal();
		
		terminalTab.onTerminalFxReady(()-> {
			System.out.println("foo");
		});
		
		tabPane.getTabs().add(terminalTab);
```

**Comment by rahmanusta** [comment]
Hi, the following module should be added https://github.com/javaterminal/TerminalFX/blob/master/README.adoc#7-run-as-java-module

**Comment by oskarmolander2** [comment]
Thank you for responding but nothing changed after adding the module.

**Comment by rahmanusta** [comment]
Can you share your demo please as maven or gradle?

**Comment by oskarmolander2** [comment]
Hi the terminaltab is now working as intented after we solved some we had with maven.
