### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ashokkumarvel** [javaterminal/TerminalFX#30]
Information:java: Errors occurred while compiling module 'terminalfx'

**Comment by ashokkumarvel** [comment]
How to run jar file ?

https://github.com/javaterminal/TerminalFX/tree/master/releases/com/kodedu/terminalfx/terminalfx/1.0.5

**Comment by rahmanusta** [comment]
We don't provide a release for TerminalFX. You should implement packaging yourself.
