### ISSUE TITLE
I am using JDK version 12 . But , an error occurs.

### ISSUE THREAD

**Issue by ashokkumarvel** [javaterminal/TerminalFX#33]
I am using JDK version 12 . But , an error occurs.

![run](https://user-images.githubusercontent.com/65845270/86210334-0d3de180-bb92-11ea-806e-2b0abe67b5de.PNG)

Error :

`"D:\install\jdk 12\bin\java.exe" --add-modules=javafx.controls,javafx.graphics --add-modules javafx.base,javafx.graphics --add-reads javafx.base=ALL-UNNAMED --add-reads javafx.graphics=ALL-UNNAMED "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=58816:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -p C:\Users\prade\.m2\repository\org\openjfx\javafx-base\12\javafx-base-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-graphics\12\javafx-graphics-12-win.jar;D:\Github\TerminalFX\target\classes;C:\Users\prade\.m2\repository\org\jetbrains\pty4j\pty4j\0.8.6\pty4j-0.8.6.jar;C:\Users\prade\.m2\repository\org\jetbrains\pty4j\purejavacomm\0.0.11.1\purejavacomm-0.0.11.1.jar;C:\Users\prade\.m2\repository\org\jetbrains\annotations\16.0.2\annotations-16.0.2.jar;C:\Users\prade\.m2\repository\com\google\guava\guava\25.1-jre\guava-25.1-jre.jar;C:\Users\prade\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\prade\.m2\repository\org\checkerframework\checker-qual\2.0.0\checker-qual-2.0.0.jar;C:\Users\prade\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.3\error_prone_annotations-2.1.3.jar;C:\Users\prade\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\prade\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\prade\.m2\repository\log4j\log4j\1.2.14\log4j-1.2.14.jar;C:\Users\prade\.m2\repository\net\java\dev\jna\jna\4.5.0\jna-4.5.0.jar;C:\Users\prade\.m2\repository\net\java\dev\jna\jna-platform\4.5.0\jna-platform-4.5.0.jar;C:\Users\prade\.m2\repository\org\apache\commons\commons-lang3\3.9\commons-lang3-3.9.jar;C:\Users\prade\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.9.8\jackson-databind-2.9.8.jar;C:\Users\prade\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.9.8\jackson-core-2.9.8.jar;C:\Users\prade\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.8\jackson-annotations-2.9.8.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-controls\12\javafx-controls-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-controls\12\javafx-controls-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-graphics\12\javafx-graphics-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-base\12\javafx-base-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-web\12\javafx-web-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-web\12\javafx-web-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-media\12\javafx-media-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-media\12\javafx-media-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-fxml\12\javafx-fxml-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-fxml\12\javafx-fxml-12-win.jar -m com.kodedu.terminalfx/com.kodedu.terminalfx.TerminalAppStarter
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
	at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Screen.java:412)
	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:152)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:835)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.graphics/com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:738)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:334)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:279)
	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:153)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:835)
`

Give a solution for this.

**Comment by rahmanusta** [comment]
You have other java versions in your system and somehow those are picked up and causes the issue. Try oracle jdk or temove other java versions in your system.

You can see the same issue here https://bugs.openjdk.java.net/browse/JDK-8231015

**Comment by ashokkumarvel** [comment]
Yes , it done . But , some warnings occurs.

`com.kodedu.terminalfx/com.kodedu.terminalfx.TerminalAppStarter
log4j:WARN No appenders could be found for logger (com.pty4j.util.ExtractedNative).
log4j:WARN Please initialize the log4j system properly.
`


1. Can I export this project as a single jar file ?

 2.Can I run this in linux?

Help !!!

**Comment by ashokkumarvel** [comment]
https://github.com/javaterminal/TerminalFX/issues/30

Can I export this project as a single jar file ?

I asked this because of issues in running jar file from your release.

**Comment by PradeepSimba** [comment]
Can I run this in linux?

**Comment by ashokkumarvel** [comment]
When I export this project  as a jar and run on linux it comes an error.

`no main manifest attribute`

How can I solve this ?

**Comment by PradeepSimba** [comment]
I also have the same error.

**Comment by poorvajappja** [comment]
`no main manifest attribute`

Error when run  the jar on linux.

**Comment by parasuraam** [comment]
The same error.

Help!!!

**Comment by rahmanusta** [comment]
Packaging a JavaFX app it is not specific to TerminalFX and it is out of our support.
