### ISSUE TITLE
How to run the jar file?

### ISSUE THREAD

**Issue by PradeepSimba** [javaterminal/TerminalFX#35]
https://github.com/javaterminal/TerminalFX/blob/master/releases/com/kodedu/terminalfx/terminalfx/1.0.5/terminalfx-1.0.5.jar

When I run this jar file it comes like this.

`
no main manifest attribute, in terminalfx-1.0.5.jar
`

**Comment by rahmanusta** [comment]
As I said previously, we don’t provide self contained jar for terminalfx. You should care yourself how to package your JavaFX application.
