### ISSUE TITLE
I runed my project with com.kodedu.terminalfx Dependency. But,  an error occured.

### ISSUE THREAD

**Issue by poorvajappja** [javaterminal/TerminalFX#39]
I runed my project with com.kodedu.terminalfx Dependency. But,  an error occured.

**UI**

![ter](https://user-images.githubusercontent.com/65843311/87218488-c362b180-c370-11ea-9dce-0b640f1c6524.PNG)

**My Project**

[terminalfxDEMO.zip](https://github.com/javaterminal/TerminalFX/files/4906406/terminalfxDEMO.zip)

**Error**

    "C:\Program Files\Java\jdk-12\bin\java.exe" --add-modules=javafx.controls,javafx.graphics --add-modules javafx.base,javafx.graphics --add-reads javafx.base=ALL-UNNAMED --add-reads javafx.graphics=ALL-UNNAMED "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\lib\idea_rt.jar=53786:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin" -Dfile.encoding=UTF-8 -p C:\Users\prade\.m2\repository\org\openjfx\javafx-base\12\javafx-base-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-graphics\12\javafx-graphics-12-win.jar;D:\jp\jTabbedTerminal-master\target\classes;C:\Users\prade\.m2\repository\org\jetbrains\pty4j\pty4j\0.8.6\pty4j-0.8.6.jar;C:\Users\prade\.m2\repository\org\jetbrains\pty4j\purejavacomm\0.0.11.1\purejavacomm-0.0.11.1.jar;C:\Users\prade\.m2\repository\org\jetbrains\annotations\16.0.2\annotations-16.0.2.jar;C:\Users\prade\.m2\repository\com\google\guava\guava\25.1-jre\guava-25.1-jre.jar;C:\Users\prade\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\prade\.m2\repository\org\checkerframework\checker-qual\2.0.0\checker-qual-2.0.0.jar;C:\Users\prade\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.3\error_prone_annotations-2.1.3.jar;C:\Users\prade\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\prade\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\prade\.m2\repository\log4j\log4j\1.2.14\log4j-1.2.14.jar;C:\Users\prade\.m2\repository\net\java\dev\jna\jna\4.5.0\jna-4.5.0.jar;C:\Users\prade\.m2\repository\net\java\dev\jna\jna-platform\4.5.0\jna-platform-4.5.0.jar;C:\Users\prade\.m2\repository\org\apache\commons\commons-lang3\3.9\commons-lang3-3.9.jar;C:\Users\prade\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.9.8\jackson-databind-2.9.8.jar;C:\Users\prade\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.9.8\jackson-core-2.9.8.jar;C:\Users\prade\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.8\jackson-annotations-2.9.8.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-base\12\javafx-base-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-controls\12\javafx-controls-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-controls\12\javafx-controls-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-fxml\12\javafx-fxml-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-fxml\12\javafx-fxml-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-graphics\12\javafx-graphics-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-media\12\javafx-media-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-media\12\javafx-media-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-swing\12\javafx-swing-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-swing\12\javafx-swing-12-win.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-web\12\javafx-web-12.jar;C:\Users\prade\.m2\repository\org\openjfx\javafx-web\12\javafx-web-12-win.jar;C:\Users\prade\.m2\repository\com\kodedu\terminalfx\terminalfx\1.1.0\terminalfx-1.1.0.jar -m jtabbedterminal.jTabbedTerminal/jtabbedterminal.jTabbedTerminal
    log4j:WARN No appenders could be found for logger (com.pty4j.util.ExtractedNative).
    log4j:WARN Please initialize the log4j system properly.
    Exception in thread "Thread-7" java.lang.NullPointerException
	at com.kodedu.terminalfx/com.kodedu.terminalfx.Terminal.lambda$command$0(Terminal.java:50)
	at java.base/java.lang.Thread.run(Thread.java:835)
    Exception in thread "Thread-9" java.lang.NullPointerException
	at com.kodedu.terminalfx/com.kodedu.terminalfx.Terminal.lambda$command$0(Terminal.java:50)
	at java.base/java.lang.Thread.run(Thread.java:835)
    Exception in thread "Thread-10" java.lang.NullPointerException
	at com.kodedu.terminalfx/com.kodedu.terminalfx.Terminal.lambda$command$0(Terminal.java:50)
	at java.base/java.lang.Thread.run(Thread.java:835)
    Exception in thread "Thread-11" java.lang.NullPointerException
	at com.kodedu.terminalfx/com.kodedu.terminalfx.Terminal.lambda$command$0(Terminal.java:50)
	at java.base/java.lang.Thread.run(Thread.java:835)
    Exception in thread "Thread-12" java.lang.NullPointerException
	at com.kodedu.terminalfx/com.kodedu.terminalfx.Terminal.lambda$command$0(Terminal.java:50)
	at java.base/java.lang.Thread.run(Thread.java:835)

    Process finished with exit code 0

How can I solve this error ?

**Comment by rahmanusta** [comment]
It successfully works here https://github.com/asciidocfx/AsciidocFX

There should be some problem in your setup

**Comment by poorvajappja** [comment]
My  project: https://github.com/javaterminal/TerminalFX/files/4906406/terminalfxDEMO.zip

Can you give more information?

I spend two week for this. But , all fails.
Help!!!

**Comment by rahmanusta** [comment]
Sorry, that’s about your setup and this is out of our support.

**Comment by poorvajappja** [comment]
This is my project.  What I am doing    wrong in this project.

**Comment by rahmanusta** [comment]
I understand but this is out of our responsibility.

**Comment by poorvajappja** [comment]
Please check this two files : https://github.com/myrlyn/jTabbedTerminal/tree/master/src/jtabbedterminal

**Comment by poorvajappja** [comment]
Help!!!
