### ISSUE TITLE
Application doesn't close 

### ISSUE THREAD

**Issue by Vladutu** [javaterminal/TerminalFX#44]
Application doesn't close because `ThreadHelper.singleExecutorService` is not closed.

**Comment by rahmanusta** [comment]
Okay, can you send a pull request to fix that issue ?

**Comment by Vladutu** [comment]
I am not able to push a branch it seems and i don't have time to investigate why, but the solution is simple:
```
    public static void shutDownExecutorService() {
        singleExecutorService.shutdown();
    }
```

**Comment by dustinkredmond** [comment]
I created Pull Request #45 to resolve this. Please review.

**Comment by dustinkredmond** [comment]
@rahmanusta, if all looks good. Please merge #45.

**Comment by rahmanusta** [comment]
Merged thanks
