### ISSUE TITLE
When I start under window, there's a random normal situation.

### ISSUE THREAD

**Issue by pinwei1900** [javaterminal/TerminalFX#6]
### Because when I was tracking the code, I found that the following code was not executed.
TerminalTab.java
```
    @WebkitCall
    public void onTerminalReady() {
        ThreadHelper.start(() -> {
            try {
                initializeProcess();
            } catch (Exception e) {
                 e.printStackTrace();
            }

        });
    }
```
### unnormal
![image](https://user-images.githubusercontent.com/16077940/34975171-88d6eb8c-facb-11e7-9d62-8b885a15acf6.png)
### normal
![image](https://user-images.githubusercontent.com/16077940/34975189-a2c8257e-facb-11e7-84fd-16b480362f87.png)

I'm new for javafx. Can you tell me what I should do to keep this code running normal?

**Comment by pinwei1900** [comment]
![image](https://user-images.githubusercontent.com/16077940/35034447-2d5a60d4-fba9-11e7-8743-b732dc289cda.png)

That solves the problem.Thanks !

**Comment by rahmanusta** [comment]
Should I delete this one?

**Comment by rahmanusta** [comment]
I guess this issue is fixed.
